name: rickandmorty
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.2
  sizer: ^2.0.15
  flutter_native_splash: ^2.3.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  shared_preferences: ^2.1.2
  go_router: ^8.1.0
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#0000"
  image: assets/images/logo.png
